import { CurriculumLesson, CefrLevel } from "@/types";

export const CEFR_LEVELS: { level: CefrLevel; label: string; description: string }[] = [
  { level: "A1", label: "Beginner", description: "Basic phrases and sentence structure" },
  { level: "A2", label: "Elementary", description: "Everyday expressions and past tense" },
  { level: "B1", label: "Intermediate", description: "Complex sentences and written past" },
  { level: "B2", label: "Upper Intermediate", description: "Abstract topics and nuance" },
  { level: "C1", label: "Advanced", description: "Implicit meaning and flexible use" },
  { level: "C2", label: "Mastery", description: "Near-native precision and style" },
];

export const CURRICULUM: CurriculumLesson[] = [
  // ════════════════════════════════════════
  // A1 — Beginner (8 lessons)
  // ════════════════════════════════════════
  {
    id: "a1-01",
    cefrLevel: "A1",
    order: 1,
    title: "Sentence Structure (SVO)",
    slug: "sentence-structure",
    description: "Learn basic German word order: Subject – Verb – Object.",
    grammarFocus: "Basic sentence structure SVO",
    prerequisites: [],
    teachContent: `In German, the basic sentence follows **Subject – Verb – Object** order, just like English.\n\n**Examples:**\n- **Ich** trinke **Kaffee**. (I drink coffee.)\n- **Er** liest **ein Buch**. (He reads a book.)\n- **Wir** kaufen **Brot**. (We buy bread.)\n\nThe verb always comes in the **second position** — this is the most important rule in German!`,
    drillPrompts: [
      "Rearrange: Buch / liest / Er / ein → ___",
      "Fill in the verb position: Maria ___ einen Apfel. (essen)",
      "Correct this: Kaffee ich trinke. → ___",
    ],
    writePrompt: "Write 2 simple sentences about what you do in the morning. Use Subject-Verb-Object order.",
    passingScore: 70,
  },
  {
    id: "a1-02",
    cefrLevel: "A1",
    order: 2,
    title: "Present Tense: sein & haben",
    slug: "sein-haben",
    description: "Conjugate the two most important German verbs.",
    grammarFocus: "Present tense conjugation of sein and haben",
    prerequisites: ["a1-01"],
    teachContent: `**sein** (to be) and **haben** (to have) are irregular and must be memorized.\n\n| | sein | haben |\n|---|---|---|\n| ich | bin | habe |\n| du | bist | hast |\n| er/sie/es | ist | hat |\n| wir | sind | haben |\n| ihr | seid | habt |\n| sie/Sie | sind | haben |\n\n**Examples:**\n- Ich **bin** müde. (I am tired.)\n- Er **hat** ein Auto. (He has a car.)`,
    drillPrompts: [
      "Ich ___ Student. (sein)",
      "Wir ___ zwei Kinder. (haben)",
      "Du ___ sehr nett. (sein)",
      "Sie ___ keine Zeit. (haben)",
    ],
    writePrompt: "Describe yourself and your family using 'sein' and 'haben'. Write 3 sentences.",
    passingScore: 70,
  },
  {
    id: "a1-03",
    cefrLevel: "A1",
    order: 3,
    title: "Regular Verb Conjugation",
    slug: "regular-verbs",
    description: "Learn the present tense pattern for regular verbs.",
    grammarFocus: "Regular verb conjugation present tense",
    prerequisites: ["a1-02"],
    teachContent: `Regular verbs follow a predictable pattern. Remove **-en** from the infinitive and add endings:\n\n| | spielen (to play) |\n|---|---|\n| ich | spiel**e** |\n| du | spiel**st** |\n| er/sie/es | spiel**t** |\n| wir | spiel**en** |\n| ihr | spiel**t** |\n| sie/Sie | spiel**en** |\n\n**More verbs:** lernen, machen, wohnen, kaufen, trinken`,
    drillPrompts: [
      "Er ___ Fußball. (spielen)",
      "Wir ___ Deutsch. (lernen)",
      "Ihr ___ in Berlin. (wohnen)",
      "Ich ___ Wasser. (trinken)",
    ],
    writePrompt: "Write 3 sentences about your daily activities using different regular verbs.",
    passingScore: 70,
  },
  {
    id: "a1-04",
    cefrLevel: "A1",
    order: 4,
    title: "Articles & Nominativ",
    slug: "articles-nominativ",
    description: "der, die, das — the three genders and the Nominativ case.",
    grammarFocus: "Nominativ case and definite articles der die das",
    prerequisites: ["a1-01"],
    teachContent: `Every German noun has a gender: **masculine (der)**, **feminine (die)**, or **neuter (das)**.\n\nIn Nominativ (subject case):\n- **der** Mann (the man)\n- **die** Frau (the woman)\n- **das** Kind (the child)\n- **die** Kinder (plural — always 'die')\n\nIndefinite articles: **ein** (m/n), **eine** (f)\n\nTip: Always learn the article WITH the noun!`,
    drillPrompts: [
      "___ Hund ist groß. (der/die/das)",
      "___ Katze schläft. (der/die/das)",
      "___ Buch ist interessant. (der/die/das)",
      "Das ist ___ Frau. (ein/eine)",
    ],
    writePrompt: "Describe 3 objects in your room. Use 'der/die/das' and 'ein/eine' correctly.",
    passingScore: 70,
  },
  {
    id: "a1-05",
    cefrLevel: "A1",
    order: 5,
    title: "Negation: nicht & kein",
    slug: "negation",
    description: "Learn to negate sentences with nicht and kein.",
    grammarFocus: "Negation with nicht and kein",
    prerequisites: ["a1-04"],
    teachContent: `**kein** negates nouns with ein/eine (or no article):\n- Ich habe **ein** Auto → Ich habe **kein** Auto.\n- Sie trinkt Kaffee → Sie trinkt **keinen** Kaffee.\n\n**nicht** negates everything else (verbs, adjectives, adverbs):\n- Er schläft **nicht**.\n- Das Buch ist **nicht** gut.\n\n**Rule of thumb:** If you can replace with 'kein', use kein. Otherwise, use nicht.`,
    drillPrompts: [
      "Ich habe ___ Bruder. (nicht/kein/keinen)",
      "Er kommt heute ___. (nicht/kein)",
      "Das ist ___ Problem. (nicht/kein)",
      "Sie isst ___ Fleisch. (nicht/kein)",
    ],
    writePrompt: "Write 3 sentences about things you DON'T have or DON'T do, using 'nicht' and 'kein'.",
    passingScore: 70,
  },
  {
    id: "a1-06",
    cefrLevel: "A1",
    order: 6,
    title: "Questions: W-Fragen & Ja/Nein",
    slug: "questions",
    description: "Form questions using W-words and yes/no structure.",
    grammarFocus: "W-questions and yes/no question word order",
    prerequisites: ["a1-03"],
    teachContent: `**Yes/No questions:** put the verb FIRST.\n- Du spielst Tennis. → **Spielst** du Tennis?\n- Er trinkt Kaffee. → **Trinkt** er Kaffee?\n\n**W-questions:** W-word + verb + subject.\n- **Wo** wohnst du? (Where do you live?)\n- **Was** machst du? (What do you do?)\n- **Wer** ist das? (Who is that?)\n- **Wann** kommst du? (When are you coming?)\n- **Wie** heißt du? (What is your name?)`,
    drillPrompts: [
      "Make a question: Du lernst Deutsch. → ___",
      "___ wohnst du? (Wo/Was/Wer)",
      "Make a question: Er heißt Thomas. → Wie ___?",
      "___ kommt heute? (Wer/Wo/Wann)",
    ],
    writePrompt: "Write 3 questions you would ask a new classmate. Use both W-questions and yes/no questions.",
    passingScore: 70,
  },
  {
    id: "a1-07",
    cefrLevel: "A1",
    order: 7,
    title: "Plural Forms",
    slug: "plural-forms",
    description: "Learn the five patterns for forming German plurals.",
    grammarFocus: "Noun plural forms",
    prerequisites: ["a1-04"],
    teachContent: `German has 5 main plural patterns:\n\n| Pattern | Singular → Plural |\n|---|---|\n| -e | der Tag → die Tag**e** |\n| -er | das Kind → die Kind**er** |\n| -n/-en | die Frau → die Frau**en** |\n| -s | das Auto → die Auto**s** |\n| – (no change) | der Lehrer → die Lehrer |\n\nSome add an **Umlaut**: der Mann → die M**ä**nner\n\nAll plurals use **die** as the article.`,
    drillPrompts: [
      "das Buch → die ___ (Bücher/Buchen/Buchs)",
      "die Lampe → die ___ (Lampen/Lampes/Lampeer)",
      "der Hund → die ___ (Hunde/Hunden/Hünder)",
      "das Auto → die ___ (Autos/Autoen/Auter)",
    ],
    writePrompt: "Write 3 sentences describing what you see in a classroom, using plural nouns.",
    passingScore: 70,
  },
  {
    id: "a1-08",
    cefrLevel: "A1",
    order: 8,
    title: "Akkusativ: Direct Objects",
    slug: "akkusativ-basics",
    description: "The Akkusativ case for direct objects — when articles change.",
    grammarFocus: "Akkusativ case for direct objects",
    prerequisites: ["a1-04", "a1-05"],
    teachContent: `The **Akkusativ** marks the direct object (the thing receiving the action).\n\nOnly **masculine** articles change:\n\n| | Nominativ | Akkusativ |\n|---|---|---|\n| masculine | **der/ein** | **den/einen** |\n| feminine | die/eine | die/eine |\n| neuter | das/ein | das/ein |\n| plural | die | die |\n\n**Examples:**\n- Ich sehe **den** Mann. (I see the man.)\n- Sie kauft **einen** Kuchen. (She buys a cake.)\n- Wir haben **das** Buch. (We have the book — neuter, no change!)`,
    drillPrompts: [
      "Ich kaufe ___ Tisch. (der→den / die / das)",
      "Er trinkt ___ Kaffee. (der→den / ein→einen)",
      "Sie liest ___ Zeitung. (der→den / die / das)",
      "Wir brauchen ___ Computer. (ein→einen / eine)",
    ],
    writePrompt: "Write 3 sentences about things you buy at a supermarket. Use masculine, feminine, and neuter nouns in the Akkusativ.",
    passingScore: 70,
  },

  // ════════════════════════════════════════
  // A2 — Elementary (8 lessons)
  // ════════════════════════════════════════
  {
    id: "a2-01",
    cefrLevel: "A2",
    order: 1,
    title: "Perfekt: Conversational Past",
    slug: "perfekt",
    description: "Talk about the past using haben/sein + past participle.",
    grammarFocus: "Perfekt tense with haben and sein",
    prerequisites: ["a1-02", "a1-03"],
    teachContent: `The **Perfekt** is the most common past tense in spoken German.\n\nFormula: **haben/sein** + **past participle** (at the end)\n\n**Regular verbs:** ge- + stem + -t\n- spielen → ge**spiel**t: Ich **habe** Fußball ge**spiel**t.\n- kaufen → ge**kauf**t: Er **hat** Brot ge**kauf**t.\n\n**Verbs of movement/change use sein:**\n- gehen → gegangen: Ich **bin** nach Hause **gegangen**.\n- fahren → gefahren: Sie **ist** nach Berlin **gefahren**.`,
    drillPrompts: [
      "Ich ___ gestern Tennis ___. (haben + spielen)",
      "Sie ___ nach München ___. (sein + fahren)",
      "Wir ___ einen Film ___. (haben + sehen → gesehen)",
      "Er ___ um 8 Uhr ___. (sein + kommen → gekommen)",
    ],
    writePrompt: "Write 3 sentences about what you did last weekend. Use Perfekt with both 'haben' and 'sein'.",
    passingScore: 70,
  },
  {
    id: "a2-02",
    cefrLevel: "A2",
    order: 2,
    title: "Modal Verbs",
    slug: "modal-verbs",
    description: "können, müssen, wollen, sollen, dürfen, mögen.",
    grammarFocus: "Modal verbs and sentence structure with modals",
    prerequisites: ["a1-03"],
    teachContent: `Modal verbs express ability, obligation, desire, etc. They push the main verb to the **end** as an infinitive.\n\n| Verb | Meaning | ich | er/sie |\n|---|---|---|---|\n| können | can | kann | kann |\n| müssen | must | muss | muss |\n| wollen | want | will | will |\n| sollen | should | soll | soll |\n| dürfen | may | darf | darf |\n\n**Structure:** Modal (pos. 2) + ... + Infinitive (end)\n- Ich **kann** Deutsch **sprechen**.\n- Du **musst** heute **arbeiten**.`,
    drillPrompts: [
      "Ich ___ Deutsch sprechen. (can)",
      "Er ___ heute arbeiten. (must)",
      "Wir ___ ins Kino gehen. (want)",
      "Du ___ hier nicht rauchen. (may not)",
    ],
    writePrompt: "Write 3 sentences about rules at your school or workplace using different modal verbs.",
    passingScore: 70,
  },
  {
    id: "a2-03",
    cefrLevel: "A2",
    order: 3,
    title: "Dativ: Indirect Objects",
    slug: "dativ",
    description: "The Dativ case — giving things to people.",
    grammarFocus: "Dativ case for indirect objects",
    prerequisites: ["a1-08"],
    teachContent: `The **Dativ** marks the indirect object (the person receiving something).\n\n| | Nominativ | Akkusativ | **Dativ** |\n|---|---|---|---|\n| masculine | der/ein | den/einen | **dem/einem** |\n| feminine | die/eine | die/eine | **der/einer** |\n| neuter | das/ein | das/ein | **dem/einem** |\n| plural | die | die | **den (+n)** |\n\n**Examples:**\n- Ich gebe **dem** Mann ein Buch. (I give the man a book.)\n- Sie hilft **der** Frau. (She helps the woman.)\n- Er schreibt **den** Kindern einen Brief. (He writes the children a letter.)`,
    drillPrompts: [
      "Ich gebe ___ Lehrer das Buch. (der→dem)",
      "Sie hilft ___ Kind. (das→dem)",
      "Er schenkt ___ Mutter Blumen. (die→der)",
      "Wir zeigen ___ Touristen die Stadt. (die→den)",
    ],
    writePrompt: "Write 3 sentences about giving or showing things to people. Use different genders in the Dativ.",
    passingScore: 70,
  },
  {
    id: "a2-04",
    cefrLevel: "A2",
    order: 4,
    title: "Two-Way Prepositions",
    slug: "wechselpraepositionen",
    description: "in, auf, an, über, unter, vor, hinter, neben, zwischen — Akkusativ or Dativ?",
    grammarFocus: "Wechselpräpositionen with Akkusativ and Dativ",
    prerequisites: ["a2-03"],
    teachContent: `These 9 prepositions use **Akkusativ for movement** (Wohin?) and **Dativ for location** (Wo?):\n\nin, auf, an, über, unter, vor, hinter, neben, zwischen\n\n**Wohin? (movement → Akkusativ)**\n- Ich gehe **in den** Park. (Where to?)\n- Er legt das Buch **auf den** Tisch.\n\n**Wo? (location → Dativ)**\n- Ich bin **im** (= in dem) Park. (Where?)\n- Das Buch liegt **auf dem** Tisch.\n\nMemory trick: **Movement = Akkusativ, Stillstand = Dativ**`,
    drillPrompts: [
      "Ich gehe in ___ Schule. (die→Akk or Dat?)",
      "Das Bild hängt an ___ Wand. (die→Akk or Dat?)",
      "Er stellt die Vase auf ___ Tisch. (der→Akk or Dat?)",
      "Die Katze sitzt unter ___ Stuhl. (der→Akk or Dat?)",
    ],
    writePrompt: "Describe your room: where things ARE (Dativ) and where you PUT them (Akkusativ). Write 4 sentences.",
    passingScore: 70,
  },
  {
    id: "a2-05",
    cefrLevel: "A2",
    order: 5,
    title: "Reflexive Verbs",
    slug: "reflexive-verbs",
    description: "sich waschen, sich freuen — when the subject acts on itself.",
    grammarFocus: "Reflexive verbs and reflexive pronouns",
    prerequisites: ["a2-03"],
    teachContent: `Reflexive verbs use a reflexive pronoun — the action reflects back to the subject.\n\n| | Pronoun |\n|---|---|\n| ich | **mich** / mir |\n| du | **dich** / dir |\n| er/sie/es | **sich** |\n| wir | **uns** |\n| ihr | **euch** |\n| sie/Sie | **sich** |\n\n**Common reflexive verbs:**\n- sich freuen (to be happy): Ich freue **mich**.\n- sich waschen (to wash): Er wäscht **sich**.\n- sich setzen (to sit down): Setz **dich**!\n- sich fühlen (to feel): Wie fühlst du **dich**?`,
    drillPrompts: [
      "Ich freue ___ auf den Urlaub. (mich/mir/sich)",
      "Er wäscht ___ die Hände. (mich/sich/uns)",
      "Wir setzen ___ an den Tisch. (sich/uns/euch)",
      "Fühlst du ___ gut? (dich/sich/mich)",
    ],
    writePrompt: "Write 3 sentences about your morning routine using reflexive verbs.",
    passingScore: 70,
  },
  {
    id: "a2-06",
    cefrLevel: "A2",
    order: 6,
    title: "Conjunctions: weil, dass, wenn",
    slug: "nebensaetze",
    description: "Subordinating conjunctions send the verb to the end.",
    grammarFocus: "Subordinating conjunctions weil dass wenn and verb-final word order",
    prerequisites: ["a1-06", "a2-02"],
    teachContent: `Subordinating conjunctions create a **Nebensatz** (subordinate clause) where the verb goes to the **END**.\n\n**weil** (because): Ich lerne Deutsch, **weil** ich in Berlin **wohne**.\n**dass** (that): Ich weiß, **dass** er krank **ist**.\n**wenn** (if/when): **Wenn** es regnet, **bleibe** ich zu Hause.\n\n**Key rule:** In the Nebensatz, the conjugated verb moves to the LAST position.\n\nMain clause: Ich bleibe zu Hause. (verb in position 2)\nNebensatz: ...weil ich müde **bin**. (verb at the end)`,
    drillPrompts: [
      "Ich lerne Deutsch, weil ich es interessant ___. (finde — position?)",
      "Er sagt, dass er morgen ___. (kommen — position?)",
      "Wenn ich Zeit ___, gehe ich spazieren. (haben — position?)",
      "Reorder: weil / er / hat / keine Zeit → ___",
    ],
    writePrompt: "Write 3 complex sentences: one with 'weil', one with 'dass', one with 'wenn'. Remember: verb goes to the end!",
    passingScore: 70,
  },
  {
    id: "a2-07",
    cefrLevel: "A2",
    order: 7,
    title: "Comparative & Superlative",
    slug: "comparison",
    description: "schneller, am schnellsten — comparing things in German.",
    grammarFocus: "Comparative and superlative adjective forms",
    prerequisites: ["a1-04"],
    teachContent: `**Comparative:** adjective + **-er** (+ als)\n- schnell → schnell**er**: Er ist schneller **als** ich.\n- groß → größ**er** (Umlaut!): Berlin ist größer als München.\n\n**Superlative:** am + adjective + **-sten**\n- schnell → **am schnellsten**: Usain Bolt läuft am schnellsten.\n- groß → **am größten**: Tokyo ist am größten.\n\n**Irregular:** gut → besser → am besten | viel → mehr → am meisten | gern → lieber → am liebsten`,
    drillPrompts: [
      "Ein Auto ist ___ als ein Fahrrad. (schnell)",
      "München ist ___ als Hamburg. (groß)",
      "Ich spiele ___ Fußball als Tennis. (gern → lieber)",
      "Das ist das ___ Restaurant in der Stadt. (gut → beste)",
    ],
    writePrompt: "Compare 3 things or people you know. Use both comparative (…er als) and superlative (am …sten).",
    passingScore: 70,
  },
  {
    id: "a2-08",
    cefrLevel: "A2",
    order: 8,
    title: "Imperative",
    slug: "imperative",
    description: "Give commands and instructions in German.",
    grammarFocus: "Imperative mood for du ihr Sie",
    prerequisites: ["a1-03"],
    teachContent: `The **Imperative** is used for commands, instructions, and requests.\n\n| | du | ihr | Sie |\n|---|---|---|---|\n| machen | **Mach**! | **Macht**! | **Machen** Sie! |\n| kommen | **Komm**! | **Kommt**! | **Kommen** Sie! |\n| lesen | **Lies**! | **Lest**! | **Lesen** Sie! |\n| sein | **Sei**! | **Seid**! | **Seien** Sie! |\n\n**Rules:**\n- du-form: remove -st ending (du machst → Mach!)\n- ihr-form: same as regular ihr (ihr macht → Macht!)\n- Sie-form: verb + Sie (Sie machen → Machen Sie!)`,
    drillPrompts: [
      "___! (kommen, du-form)",
      "___ Sie bitte Platz! (nehmen, Sie-form)",
      "___ leise! (sein, ihr-form)",
      "___ das Buch! (lesen, du-form)",
    ],
    writePrompt: "Write instructions for making a sandwich or tea. Use du-form imperatives for each step.",
    passingScore: 70,
  },

  // ════════════════════════════════════════
  // B1 — Intermediate (8 lessons)
  // ════════════════════════════════════════
  {
    id: "b1-01",
    cefrLevel: "B1",
    order: 1,
    title: "Präteritum: Written Past",
    slug: "praeteritum",
    description: "The simple past tense used in written German.",
    grammarFocus: "Präteritum tense for regular and irregular verbs",
    prerequisites: ["a2-01"],
    teachContent: `The **Präteritum** is the written past tense, common in stories and formal writing.\n\n**Regular:** stem + -te\n- spielen → ich spiel**te**, er spiel**te**\n- lernen → ich lern**te**\n\n**Irregular (strong verbs):** vowel change\n- gehen → ich **ging**\n- sehen → ich **sah**\n- kommen → ich **kam**\n- schreiben → ich **schrieb**\n\n**sein/haben always use Präteritum in speech too:**\n- Ich **war** müde. (not: bin gewesen)\n- Er **hatte** keine Zeit. (not: hat gehabt)`,
    drillPrompts: [
      "Er ___ gestern nach Berlin. (gehen → Prät.)",
      "Ich ___ das Buch sehr gut. (finden → Prät.)",
      "Sie ___ den ganzen Tag. (arbeiten → Prät.)",
      "Wir ___ kein Geld. (haben → Prät.)",
    ],
    writePrompt: "Retell a short story from your childhood using Präteritum. Write 4-5 sentences.",
    passingScore: 70,
  },
  {
    id: "b1-02",
    cefrLevel: "B1",
    order: 2,
    title: "Genitiv",
    slug: "genitiv",
    description: "The genitive case — showing possession and relationships.",
    grammarFocus: "Genitiv case for possession",
    prerequisites: ["a2-03"],
    teachContent: `The **Genitiv** shows possession — like English "'s" or "of".\n\n| | Nominativ | **Genitiv** |\n|---|---|---|\n| masculine | der/ein | **des/eines** (+s/es) |\n| feminine | die/eine | **der/einer** |\n| neuter | das/ein | **des/eines** (+s/es) |\n| plural | die | **der** |\n\n**Masculine/neuter nouns add -s or -es:**\n- Das Auto **des Mannes** (the man's car)\n- Die Farbe **des Buches** (the color of the book)\n\n**Feminine/plural — no noun ending:**\n- Die Tasche **der Frau** (the woman's bag)\n- Die Spielzeuge **der Kinder** (the children's toys)`,
    drillPrompts: [
      "Das Haus ___ Lehrers ist groß. (der→des)",
      "Die Mutter ___ Kindes ist hier. (das→des)",
      "Die Farbe ___ Blume ist rot. (die→der)",
      "Die Bücher ___ Studenten sind neu. (die pl.→der)",
    ],
    writePrompt: "Describe possessions of 3 people you know. Use the Genitiv case.",
    passingScore: 70,
  },
  {
    id: "b1-03",
    cefrLevel: "B1",
    order: 3,
    title: "Relative Clauses",
    slug: "relativsaetze",
    description: "Combine sentences using der/die/das as relative pronouns.",
    grammarFocus: "Relative clauses with relative pronouns",
    prerequisites: ["a2-06"],
    teachContent: `Relative clauses add information about a noun. They start with a **relative pronoun** and the verb goes to the **end**.\n\nThe relative pronoun matches the **gender/number** of the noun it refers to, and the **case** depends on its role in the relative clause.\n\n| | Nom. | Akk. | Dat. |\n|---|---|---|---|\n| m. | der | den | dem |\n| f. | die | die | der |\n| n. | das | das | dem |\n| pl. | die | die | denen |\n\n**Examples:**\n- Der Mann, **der** dort steht, ist mein Lehrer. (Nom.)\n- Das Buch, **das** ich lese, ist spannend. (Akk.)\n- Die Frau, **der** ich helfe, ist nett. (Dat.)`,
    drillPrompts: [
      "Der Mann, ___ dort steht, ist nett. (der/den/dem)",
      "Das Buch, ___ ich lese, ist gut. (der/das/dem)",
      "Die Frau, ___ ich helfe, ist meine Nachbarin. (die/der/den)",
      "Die Kinder, ___ im Park spielen, sind laut. (der/die/denen)",
    ],
    writePrompt: "Write 3 sentences describing people or things using relative clauses.",
    passingScore: 70,
  },
  {
    id: "b1-04",
    cefrLevel: "B1",
    order: 4,
    title: "Passive Voice",
    slug: "passiv",
    description: "Vorgangspassiv — when the action matters more than who does it.",
    grammarFocus: "Passive voice with werden plus past participle",
    prerequisites: ["a2-01", "b1-01"],
    teachContent: `The **Passive** shifts focus from who does something to what is done.\n\n**Formula:** werden + past participle\n\n**Present:** Das Haus **wird** gebaut. (The house is being built.)\n**Präteritum:** Das Haus **wurde** gebaut. (The house was built.)\n**Perfekt:** Das Haus **ist** gebaut **worden**. (The house has been built.)\n\n**By whom? → von + Dativ:**\n- Das Buch wird **von dem Autor** geschrieben.\n\n**Active → Passive:**\n- Der Koch kocht das Essen. → Das Essen **wird** (vom Koch) **gekocht**.`,
    drillPrompts: [
      "Das Auto ___ repariert. (werden — Präsens)",
      "Der Brief ___ gestern geschrieben. (werden — Prät.)",
      "Active→Passive: Man spricht hier Deutsch. → Hier ___ Deutsch ___.",
      "Die Tür ___ von ihm geöffnet ___. (Perfekt Passiv)",
    ],
    writePrompt: "Write 3 sentences about how things are made or done in your country. Use the Passive voice.",
    passingScore: 70,
  },
  {
    id: "b1-05",
    cefrLevel: "B1",
    order: 5,
    title: "Konjunktiv II",
    slug: "konjunktiv-ii",
    description: "Express wishes, hypotheticals, and polite requests.",
    grammarFocus: "Konjunktiv II with würde and common irregular forms",
    prerequisites: ["a2-02"],
    teachContent: `**Konjunktiv II** expresses unreal situations, wishes, and polite requests.\n\n**Most verbs:** würde + infinitive\n- Ich **würde** gern nach Japan **reisen**.\n- **Würdest** du mir bitte **helfen**?\n\n**Common irregular forms (preferred):**\n- sein → wäre: Ich **wäre** gern reich.\n- haben → hätte: Ich **hätte** gern ein Eis.\n- können → könnte: **Könntest** du das Fenster öffnen?\n- müssen → müsste: Ich **müsste** eigentlich lernen.\n\n**Wishes with wenn:**\n- **Wenn** ich reich **wäre**, **würde** ich um die Welt **reisen**.`,
    drillPrompts: [
      "Ich ___ gern nach Spanien reisen. (würde)",
      "Wenn ich Zeit ___, würde ich lesen. (haben → Konj.II)",
      "___ du mir bitte helfen? (können → Konj.II)",
      "Ich ___ gern ein neues Auto. (haben → Konj.II)",
    ],
    writePrompt: "Write 3 wishes using 'Wenn ich... wäre/hätte, würde ich...' and one polite request using Konjunktiv II.",
    passingScore: 70,
  },
  {
    id: "b1-06",
    cefrLevel: "B1",
    order: 6,
    title: "Infinitive Clauses: um...zu, ohne...zu",
    slug: "infinitivsaetze",
    description: "Express purpose and manner with infinitive constructions.",
    grammarFocus: "Infinitive clauses with um zu ohne zu anstatt zu",
    prerequisites: ["a2-06"],
    teachContent: `Infinitive clauses use **zu + infinitive** at the end.\n\n**um...zu** (in order to):\n- Ich lerne Deutsch, **um** in Deutschland **zu arbeiten**.\n\n**ohne...zu** (without doing):\n- Er ging, **ohne** sich **zu verabschieden**.\n\n**anstatt...zu** (instead of doing):\n- Sie spielt, **anstatt zu lernen**.\n\n**With separable verbs, zu goes between prefix and verb:**\n- Ich versuche, früh **aufzustehen**. (auf|stehen)`,
    drillPrompts: [
      "Ich lerne Deutsch, ___ in Berlin ___ arbeiten. (um...zu)",
      "Er ging weg, ___ etwas ___ sagen. (ohne...zu)",
      "Sie schaut fern, ___ ___ lernen. (anstatt...zu)",
      "Ich versuche, früh ___. (aufstehen → with zu)",
    ],
    writePrompt: "Write 3 sentences about your goals: why you do things (um...zu) and what you do instead of other things (anstatt...zu).",
    passingScore: 70,
  },
  {
    id: "b1-07",
    cefrLevel: "B1",
    order: 7,
    title: "N-Deklination",
    slug: "n-deklination",
    description: "Masculine nouns that add -(e)n in every case except Nominativ.",
    grammarFocus: "N-Deklination for weak masculine nouns",
    prerequisites: ["b1-02"],
    teachContent: `Some masculine nouns add **-(e)n** in Akkusativ, Dativ, and Genitiv.\n\n| Case | der Student |\n|---|---|\n| Nom. | der **Student** |\n| Akk. | den **Studenten** |\n| Dat. | dem **Studenten** |\n| Gen. | des **Studenten** |\n\n**Which nouns?** Mostly masculine nouns ending in:\n- **-e**: der Junge, der Kollege, der Kunde\n- **-ant/-ent**: der Student, der Patient\n- **-ist**: der Tourist, der Polizist\n- **-at**: der Soldat, der Diplomat\n- Also: der Herr (→ Herrn), der Mensch (→ Menschen), der Nachbar (→ Nachbarn)`,
    drillPrompts: [
      "Ich kenne den ___. (Student)",
      "Er hilft dem ___. (Kollege → Kollegen)",
      "Die Rechnung des ___ ist hoch. (Patient → Patienten)",
      "Fragen Sie den ___! (Herr → Herrn)",
    ],
    writePrompt: "Write 3 sentences using N-Deklination nouns in different cases (Akkusativ, Dativ, Genitiv).",
    passingScore: 70,
  },
  {
    id: "b1-08",
    cefrLevel: "B1",
    order: 8,
    title: "Adjective Declension (Full)",
    slug: "adjektivdeklination",
    description: "All three patterns: after der, after ein, and without article.",
    grammarFocus: "Full adjective declension with definite indefinite and zero article",
    prerequisites: ["a1-08", "a2-03", "b1-02"],
    teachContent: `Adjectives before nouns change their ending based on the article type and case.\n\n**After der/die/das (weak):**\nMostly **-e** or **-en**\n- der groß**e** Mann, die groß**e** Frau\n- den groß**en** Mann (Akk.), dem groß**en** Mann (Dat.)\n\n**After ein/eine/kein (mixed):**\n- ein groß**er** Mann (Nom. m.), eine groß**e** Frau\n- ein groß**es** Kind (Nom. n.)\n\n**Without article (strong):**\n- groß**er** Mann, groß**e** Frau, groß**es** Kind\n- kalt**en** Kaffee (Akk. m.)\n\nTip: If the article shows the gender, the adjective is weak (-e/-en). If not, the adjective must show it (strong endings).`,
    drillPrompts: [
      "der klein___ Hund (Nom.)",
      "ein alt___ Buch (Nom. n.)",
      "mit frisch___ Brot (Dat. without article)",
      "die nett___ Lehrerin (Akk.)",
    ],
    writePrompt: "Describe 3 people or objects using adjectives before nouns. Try all three patterns (after der, after ein, no article).",
    passingScore: 70,
  },

  // ════════════════════════════════════════
  // B2 — Upper Intermediate (8 lessons)
  // ════════════════════════════════════════
  {
    id: "b2-01",
    cefrLevel: "B2",
    order: 1,
    title: "Konjunktiv I: Indirect Speech",
    slug: "konjunktiv-i",
    description: "Report what someone said using Konjunktiv I.",
    grammarFocus: "Konjunktiv I for indirect speech",
    prerequisites: ["b1-05"],
    teachContent: `**Konjunktiv I** is used in formal writing and news to report speech.\n\nFormed from the infinitive stem + endings:\n- er sag**e** (from sagen), er hab**e**, er sei (sein)\n\n**Direct:** Er sagt: \"Ich **bin** krank.\"\n**Indirect:** Er sagt, er **sei** krank.\n\n**Direct:** Sie sagt: \"Ich **habe** keine Zeit.\"\n**Indirect:** Sie sagt, sie **habe** keine Zeit.\n\nWhen Konjunktiv I = indicative (ich habe = ich habe), use Konjunktiv II instead:\n- Sie sagen, sie **hätten** keine Zeit. (not: haben)`,
    drillPrompts: [
      "Er sagt, er ___ müde. (sein → Konj.I)",
      "Sie berichtet, sie ___ das Buch gelesen. (haben → Konj.I)",
      "Der Minister sagt, die Wirtschaft ___ stabil. (sein → Konj.I)",
      "Die Schüler sagen, sie ___ keine Hausaufgaben. (haben → Konj.I or II?)",
    ],
    writePrompt: "Report 3 things that people said today using Konjunktiv I indirect speech.",
    passingScore: 70,
  },
  {
    id: "b2-02",
    cefrLevel: "B2",
    order: 2,
    title: "Participial Constructions",
    slug: "partizipialkonstruktionen",
    description: "Use Partizip I and Partizip II as adjectives before nouns.",
    grammarFocus: "Partizip I and Partizip II as adjective modifiers",
    prerequisites: ["b1-08"],
    teachContent: `Participles can be used as adjectives before nouns, adding complex information.\n\n**Partizip I** (ongoing action): infinitive + **d** + adjective ending\n- das schlafend**e** Kind (the sleeping child)\n- die singend**en** Vögel (the singing birds)\n\n**Partizip II** (completed action): past participle + adjective ending\n- das geöffnet**e** Fenster (the opened window)\n- der geschrieben**e** Brief (the written letter)\n\n**Extended attributes** (very common in written German):\n- Die **von vielen Menschen besuchte** Ausstellung... (The exhibition visited by many people...)`,
    drillPrompts: [
      "das (schlafen) ___ Kind",
      "der (schreiben → Partizip II) ___ Brief",
      "die (lachen) ___ Frau",
      "das (öffnen → Partizip II) ___ Fenster",
    ],
    writePrompt: "Write 3 sentences using participial constructions — at least one with Partizip I and one with Partizip II.",
    passingScore: 70,
  },
  {
    id: "b2-03",
    cefrLevel: "B2",
    order: 3,
    title: "Double Connectors",
    slug: "doppelkonjunktionen",
    description: "je...desto, sowohl...als auch, weder...noch, entweder...oder.",
    grammarFocus: "Paired conjunctions and their word order",
    prerequisites: ["a2-06"],
    teachContent: `**Double connectors** connect two ideas with a paired structure.\n\n**je...desto/umso** (the more...the more):\n- **Je** mehr ich lerne, **desto** besser verstehe ich.\n- Word order: je + comparative + verb-last, desto + comparative + verb-second\n\n**sowohl...als auch** (both...and):\n- Er spricht **sowohl** Deutsch **als auch** Englisch.\n\n**weder...noch** (neither...nor):\n- Sie trinkt **weder** Kaffee **noch** Tee.\n\n**entweder...oder** (either...or):\n- **Entweder** kommst du mit, **oder** du bleibst hier.\n- Note: after entweder, verb can be in position 2 or inverted.`,
    drillPrompts: [
      "___ mehr ich übe, ___ besser werde ich. (je...desto)",
      "Er spricht ___ Deutsch ___ Französisch. (sowohl...als auch)",
      "Ich trinke ___ Kaffee ___ Tee. (weder...noch)",
      "___ du kommst mit, ___ ich gehe allein. (entweder...oder)",
    ],
    writePrompt: "Write 4 sentences, one for each double connector: je...desto, sowohl...als auch, weder...noch, entweder...oder.",
    passingScore: 70,
  },
  {
    id: "b2-04",
    cefrLevel: "B2",
    order: 4,
    title: "Nominalization",
    slug: "nominalisierung",
    description: "Turn verbs and adjectives into nouns — a key feature of formal German.",
    grammarFocus: "Nominalization of verbs and adjectives",
    prerequisites: ["b1-08"],
    teachContent: `German loves turning verbs and adjectives into nouns. This is extremely common in formal and academic writing.\n\n**Verbs → Nouns** (always neuter, always capitalized):\n- lesen → **das Lesen** (reading)\n- schwimmen → **das Schwimmen** (swimming)\n- Beim **Lesen** lerne ich viel. (While reading, I learn a lot.)\n\n**Adjectives → Nouns** (with adjective declension!):\n- krank → der/die **Kranke** (the sick person)\n- deutsch → der/die **Deutsche** (the German person)\n- neu → etwas **Neues** (something new)\n- gut → nichts **Gutes** (nothing good)\n\n**Common suffixes:** -ung (die Entscheidung), -heit/-keit (die Freiheit, die Möglichkeit)`,
    drillPrompts: [
      "Beim ___ lerne ich neue Wörter. (lesen → Nominalisierung)",
      "Der ___ muss zum Arzt. (krank → Nom. mask.)",
      "Gibt es etwas ___? (neu → Nom. after etwas)",
      "Die ___ ist schwer. (entscheiden → Nominalisierung with -ung)",
    ],
    writePrompt: "Rewrite 3 casual sentences in a more formal style using nominalization.",
    passingScore: 70,
  },
  {
    id: "b2-05",
    cefrLevel: "B2",
    order: 5,
    title: "Extended Attributes",
    slug: "erweiterte-attribute",
    description: "Pack information before a noun — the hallmark of German academic prose.",
    grammarFocus: "Extended pre-noun attributes in formal German",
    prerequisites: ["b2-02"],
    teachContent: `German can pack entire clauses BEFORE a noun, between the article and the noun.\n\n**Simple:** der **neue** Film\n**Extended:** der **gestern im Kino gezeigte** Film (the film shown yesterday in the cinema)\n\n**Structure:** article + (modifier + participle) + noun\n\n**More examples:**\n- die **von der Regierung beschlossene** Reform\n- ein **für alle Studenten gültiges** Angebot\n- der **seit drei Jahren in Berlin lebende** Mann\n\nThis is very common in newspapers, academic texts, and official documents. In spoken German, you'd use a relative clause instead.`,
    drillPrompts: [
      "Relative clause → Extended: Die Reform, die von der Regierung beschlossen wurde → die ___ Reform",
      "der Film, der gestern gezeigt wurde → der ___ Film",
      "Identify: 'Das von vielen Schülern gelesene Buch' → Who reads? What is read?",
      "Build: ein Angebot / gültig für alle / neu → ein ___",
    ],
    writePrompt: "Rewrite 3 sentences with relative clauses as extended attributes. Then write one of your own.",
    passingScore: 70,
  },
  {
    id: "b2-06",
    cefrLevel: "B2",
    order: 6,
    title: "Subjunctive in Polite Forms",
    slug: "hoeflichkeitsformen",
    description: "Advanced politeness strategies beyond basic Konjunktiv II.",
    grammarFocus: "Polite subjunctive forms and hedging strategies",
    prerequisites: ["b1-05"],
    teachContent: `German has a rich system of polite hedging using Konjunktiv II and modal verbs.\n\n**Graded politeness (most → least direct):**\n1. Mach das Fenster zu! (Imperative — direct)\n2. Kannst du das Fenster zumachen? (Indikativ — neutral)\n3. Könntest du das Fenster zumachen? (Konj. II — polite)\n4. Würdest du vielleicht das Fenster zumachen? (very polite)\n5. Wäre es möglich, das Fenster zuzumachen? (formal)\n6. Dürfte ich Sie bitten, das Fenster zuzumachen? (very formal)\n\n**Other hedging tools:**\n- Ich **hätte** gern... (I would like...)\n- **Wären** Sie so freundlich...? (Would you be so kind...?)\n- Ich **würde** vorschlagen, dass... (I would suggest that...)`,
    drillPrompts: [
      "Make polite: 'Gib mir das Buch.' → ___ du mir bitte das Buch geben?",
      "Formal request: close the door → ___ es möglich, die Tür ___?",
      "Polite suggestion: 'Wir gehen ins Kino.' → Ich ___ vorschlagen, dass wir...",
      "Order at restaurant: 'Ich will Kaffee.' → Ich ___ gern einen Kaffee.",
    ],
    writePrompt: "Write the same request in 3 politeness levels: casual (to a friend), polite (to a colleague), very formal (to a professor).",
    passingScore: 70,
  },
  {
    id: "b2-07",
    cefrLevel: "B2",
    order: 7,
    title: "Futur II",
    slug: "futur-ii",
    description: "Express assumptions about the past and future completion.",
    grammarFocus: "Futur II for past assumptions and future completion",
    prerequisites: ["a2-01", "b1-01"],
    teachContent: `**Futur II** has two uses:\n\n**1. Future completion** (will have done):\nFormula: werden + Partizip II + haben/sein\n- Bis morgen **werde** ich das Buch gelesen **haben**.\n- Um 20 Uhr **wird** er angekommen **sein**.\n\n**2. Assumption about the past** (must have done — more common!):\n- Er **wird** wohl verschlafen **haben**. (He probably overslept.)\n- Sie **wird** den Bus verpasst **haben**. (She must have missed the bus.)\n\nThe assumption use is similar to English \"must have\" or \"probably did.\"`,
    drillPrompts: [
      "Bis Freitag ___ ich die Arbeit geschrieben ___. (werden + haben)",
      "Er ist nicht da. Er ___ wohl krank gewesen ___. (assumption)",
      "Um 18 Uhr ___ wir angekommen ___. (future completion)",
      "Sie hat nicht geantwortet. Sie ___ es vergessen ___. (assumption)",
    ],
    writePrompt: "Write 2 sentences about things you will have completed by next month, and 2 assumptions about why something happened.",
    passingScore: 70,
  },
  {
    id: "b2-08",
    cefrLevel: "B2",
    order: 8,
    title: "Verb-Preposition Combinations",
    slug: "verb-praeposition",
    description: "sich freuen auf, warten auf, denken an — fixed combinations.",
    grammarFocus: "Verbs with fixed prepositions and da-/wo-compounds",
    prerequisites: ["a2-04", "a2-05"],
    teachContent: `Many German verbs require a specific preposition (often different from English!).\n\n**Common combinations:**\n- warten **auf** + Akk. (wait for): Ich warte **auf** den Bus.\n- sich freuen **auf** + Akk. (look forward to): Ich freue mich **auf** den Urlaub.\n- sich freuen **über** + Akk. (be happy about): Ich freue mich **über** das Geschenk.\n- denken **an** + Akk. (think about): Ich denke **an** dich.\n- Angst haben **vor** + Dat. (be afraid of): Ich habe Angst **vor** Spinnen.\n\n**da-compounds** (for things): darauf, darüber, daran\n- Ich freue mich **darauf**. (I'm looking forward to it.)\n\n**wo-compounds** (for questions): worauf, worüber, woran\n- **Worauf** wartest du? (What are you waiting for?)`,
    drillPrompts: [
      "Ich warte ___ den Bus. (auf/für/an)",
      "Sie freut sich ___ das Geschenk. (auf/über/für)",
      "Ich denke oft ___ meine Familie. (an/über/auf)",
      "Ich freue mich darauf. → ___ freust du dich? (wo-compound)",
    ],
    writePrompt: "Write 4 sentences using different verb-preposition combinations. Include at least one da-compound and one wo-compound question.",
    passingScore: 70,
  },

  // ════════════════════════════════════════
  // C1 — Advanced (6 lessons)
  // ════════════════════════════════════════
  {
    id: "c1-01",
    cefrLevel: "C1",
    order: 1,
    title: "Advanced Passive Constructions",
    slug: "advanced-passiv",
    description: "Zustandspassiv, subjektloses Passiv, alternatives to Passive.",
    grammarFocus: "Zustandspassiv subjektloses Passiv and passive alternatives",
    prerequisites: ["b1-04"],
    teachContent: `Beyond Vorgangspassiv (werden + PP), German has more passive forms:\n\n**Zustandspassiv** (state, not process): sein + PP\n- Die Tür **ist** geöffnet. (The door is open — state.)\n- Die Tür **wird** geöffnet. (The door is being opened — process.)\n\n**Subjektloses Passiv** (no subject!):\n- Hier **wird** nicht geraucht. (No smoking here.)\n- Es **wurde** viel gelacht. (There was a lot of laughing.)\n\n**Passive alternatives:**\n- sich lassen + Inf.: Das **lässt sich** machen. (That can be done.)\n- sein + zu + Inf.: Das Buch **ist** leicht **zu lesen**. (The book is easy to read.)\n- -bar adjectives: Das ist **machbar**. (That is doable.)`,
    drillPrompts: [
      "Zustandspassiv: Das Fenster ___ geschlossen. (ist/wird)",
      "Subjektloses Passiv: Hier ___ nicht geraucht. (wird/ist)",
      "Passive alternative: Man kann das machen. → Das ___ sich machen.",
      "Passive alternative: Man kann das Buch lesen. → Das Buch ist ___ ___.",
    ],
    writePrompt: "Write 4 sentences: one Zustandspassiv, one subjektloses Passiv, one with 'sich lassen', one with 'sein + zu + Infinitiv'.",
    passingScore: 70,
  },
  {
    id: "c1-02",
    cefrLevel: "C1",
    order: 2,
    title: "Modal Particles",
    slug: "modalpartikeln",
    description: "doch, mal, ja, eben, halt, eigentlich — the soul of spoken German.",
    grammarFocus: "Modal particles and their pragmatic meanings",
    prerequisites: ["b2-06"],
    teachContent: `Modal particles add **emotional nuance** and are what make German sound natural.\n\n**doch** (contradiction/emphasis):\n- Das ist **doch** nicht wahr! (That's just not true!)\n- Komm **doch** mit! (Do come along! — encouraging)\n\n**mal** (softening):\n- Schau **mal**! (Take a look! — friendly)\n- Kannst du **mal** helfen? (Can you help for a sec?)\n\n**ja** (shared knowledge):\n- Du weißt **ja**, dass... (You know, of course, that...)\n- Das ist **ja** toll! (That's great! — surprise)\n\n**eigentlich** (actually/fundamentally):\n- Was machst du **eigentlich** beruflich? (What do you actually do?)\n\n**halt/eben** (resignation/matter-of-fact):\n- Das ist **halt/eben** so. (That's just how it is.)`,
    drillPrompts: [
      "Komm ___ mit! (encouraging → doch/mal)",
      "Das ist ___ toll! (surprised → ja/doch)",
      "Kannst du ___ kurz helfen? (softening → mal/ja)",
      "Das ist ___ so. (resignation → halt/eben)",
    ],
    writePrompt: "Write 4 short dialogue lines, each using a different modal particle (doch, mal, ja, halt). Explain the nuance in each.",
    passingScore: 70,
  },
  {
    id: "c1-03",
    cefrLevel: "C1",
    order: 3,
    title: "Funktionsverbgefüge",
    slug: "funktionsverben",
    description: "in Betracht ziehen, zur Verfügung stehen — formal verb structures.",
    grammarFocus: "Functional verb structures in formal and academic German",
    prerequisites: ["b2-04"],
    teachContent: `**Funktionsverbgefüge (FVG)** are fixed noun-verb combinations used in formal/academic German.\n\nThe verb loses its original meaning and the noun carries the action.\n\n| Simple verb | FVG equivalent |\n|---|---|\n| fragen | eine Frage **stellen** |\n| entscheiden | eine Entscheidung **treffen** |\n| beeinflussen | Einfluss **nehmen** auf |\n| berücksichtigen | in Betracht **ziehen** |\n| verfügbar sein | zur Verfügung **stehen** |\n| helfen | Hilfe **leisten** |\n| kritisieren | Kritik **üben** an |\n\n**Why use them?** They sound more formal and allow more precise modification:\n- Er stellte eine **wichtige** Frage. (He asked an important question.)`,
    drillPrompts: [
      "Simple → FVG: 'entscheiden' → eine Entscheidung ___",
      "FVG → Simple: 'eine Frage stellen' → ___",
      "Das Buch steht Ihnen zur ___ .",
      "Die Regierung nimmt ___ auf die Wirtschaft.",
    ],
    writePrompt: "Rewrite 3 simple sentences using Funktionsverbgefüge to make them more formal.",
    passingScore: 70,
  },
  {
    id: "c1-04",
    cefrLevel: "C1",
    order: 4,
    title: "Register Shifting",
    slug: "register",
    description: "Switch between informal, formal, and academic registers.",
    grammarFocus: "Register awareness and style shifting formal informal academic",
    prerequisites: ["b2-06", "c1-03"],
    teachContent: `German has distinct registers. The same idea is expressed very differently:\n\n**Informal (spoken):**\nIch hab das Buch gelesen. War echt gut.\n\n**Standard (written):**\nIch habe das Buch gelesen. Es war wirklich gut.\n\n**Formal (business):**\nIch habe das genannte Werk zur Kenntnis genommen. Es hat mich sehr angesprochen.\n\n**Academic:**\nDas vorliegende Werk wurde einer eingehenden Lektüre unterzogen. Es weist erhebliche Qualitäten auf.\n\n**Key shifts:**\n- Contractions: hab → habe, ist's → ist es\n- Passive frequency increases with formality\n- Funktionsverbgefüge replace simple verbs\n- Modal particles decrease in formal writing\n- Nominalization increases dramatically`,
    drillPrompts: [
      "Formal → Informal: 'Ich möchte Sie bitten, mir behilflich zu sein.' → ___",
      "Informal → Formal: 'Kannst du mir mal helfen?' → ___",
      "Academic register: 'We looked at the problem.' → Das Problem ___ einer Untersuchung ___.",
      "Identify register: 'Es wäre wünschenswert, wenn...' → (informal/formal/academic?)",
    ],
    writePrompt: "Write the same message in 3 registers: a text to a friend, an email to your boss, and a paragraph for an academic paper.",
    passingScore: 70,
  },
  {
    id: "c1-05",
    cefrLevel: "C1",
    order: 5,
    title: "Concessive Clauses",
    slug: "konzessivsaetze",
    description: "obwohl, trotzdem, dennoch, wenn auch — expressing contrast and concession.",
    grammarFocus: "Concessive clauses and connectors",
    prerequisites: ["a2-06", "b2-03"],
    teachContent: `Concessive clauses express a contrast: something happens DESPITE something else.\n\n**Subordinating (verb-final):**\n- **Obwohl** es regnet, gehe ich spazieren.\n- **Obgleich/Obschon** (formal variants of obwohl)\n- **Wenn** er **auch** müde ist, arbeitet er weiter.\n\n**Adverbs (verb-second):**\n- Es regnet. **Trotzdem** gehe ich spazieren.\n- Er ist müde. **Dennoch/Nichtsdestotrotz** arbeitet er weiter.\n\n**Preposition:**\n- **Trotz** des Regens gehe ich spazieren. (trotz + Genitiv)\n\n**Concessive with so...auch:**\n- **So** schwer es **auch** ist, ich gebe nicht auf.`,
    drillPrompts: [
      "___ es kalt ist, gehe ich joggen. (obwohl/trotzdem)",
      "Es regnet. ___ gehen wir raus. (trotzdem/obwohl)",
      "___ des schlechten Wetters... (trotz — with Genitiv)",
      "___ müde er auch war, er arbeitete weiter. (So...auch)",
    ],
    writePrompt: "Write 4 sentences about challenges you face but overcome. Use obwohl, trotzdem, trotz, and so...auch.",
    passingScore: 70,
  },
  {
    id: "c1-06",
    cefrLevel: "C1",
    order: 6,
    title: "Advanced Word Order",
    slug: "advanced-word-order",
    description: "Inversion, Mittelfeld ordering, Nachfeld, and emphasis through position.",
    grammarFocus: "Advanced word order Mittelfeld Nachfeld emphasis and information structure",
    prerequisites: ["a2-06", "b1-03"],
    teachContent: `German word order is flexible but follows information-structure rules.\n\n**Vorfeld (position 1):** What you put first gets emphasis/topic status.\n- **Gestern** habe ich ihn gesehen. (Topic: when)\n- **Ihn** habe ich gestern gesehen. (Topic: him specifically)\n\n**Mittelfeld ordering (Te-Ka-Mo-Lo):**\nTemporal – Kausal – Modal – Lokal\n- Er fährt **morgen** (T) **wegen der Arbeit** (K) **mit dem Zug** (M) **nach Berlin** (L).\n\n**Nachfeld** (after the verb bracket — for heavy elements):\n- Ich habe gestern den Mann **getroffen**, **der dir geholfen hat**.\n\n**Emphatic inversion:**\n- Gelesen habe ich das Buch schon. (I DID read the book already.)`,
    drillPrompts: [
      "Reorder (TeKaMoLo): Er fährt / nach München / mit dem Auto / morgen → ___",
      "Emphasize 'gestern': Ich habe ihn gestern getroffen. → ___",
      "Move to Nachfeld: Ich habe den Mann, der mir geholfen hat, gesehen. → ___",
      "What's emphasized? 'Dem Professor hat sie das Buch gegeben.' → ___",
    ],
    writePrompt: "Write the same event 3 times, each time emphasizing a different element by changing the Vorfeld.",
    passingScore: 70,
  },

  // ════════════════════════════════════════
  // C2 — Mastery (6 lessons)
  // ════════════════════════════════════════
  {
    id: "c2-01",
    cefrLevel: "C2",
    order: 1,
    title: "Nuanced Konjunktiv Usage",
    slug: "nuanced-konjunktiv",
    description: "Distinguish subtle Konjunktiv I/II uses and archaic subjunctive.",
    grammarFocus: "Nuanced Konjunktiv I and II usage and archaic subjunctive forms",
    prerequisites: ["b2-01", "b1-05"],
    teachContent: `At C2, you master the full Konjunktiv system.\n\n**Konjunktiv I vs II in indirect speech:**\nUse K1 when forms are unambiguous; switch to K2 when K1 = Indikativ:\n- Er sagt, er **komme** morgen. (K1 — clear)\n- Sie sagen, sie **kämen** morgen. (K2 — because 'kommen' = K1 'kommen')\n\n**Irrealis of the past:**\n- **Hätte** ich das gewusst, **wäre** ich gekommen.\n- Wenn er nicht **geholfen hätte**, hätten wir es nicht **geschafft**.\n\n**Literary/archaic forms:**\n- Er fragte, ob sie käme. (formal style)\n- Man nehme drei Eier... (recipe Konjunktiv I — impersonal instruction)\n\n**Subtle hedging:**\n- Das **dürfte** stimmen. (That's probably right — epistemic)\n- Ich **möchte** meinen... (I would think...)`,
    drillPrompts: [
      "Indirect: 'Ich komme morgen.' (er) → Er sagt, er ___ morgen.",
      "Indirect: 'Wir haben keine Zeit.' (sie pl.) → Sie sagen, sie ___ keine Zeit.",
      "Past irrealis: Wenn ich es ___, hätte ich anders gehandelt. (wissen)",
      "Epistemic: 'Das ist wahrscheinlich richtig.' → Das ___ stimmen.",
    ],
    writePrompt: "Write a short news paragraph (4-5 sentences) reporting what a politician said, using correct Konjunktiv I/II switching.",
    passingScore: 75,
  },
  {
    id: "c2-02",
    cefrLevel: "C2",
    order: 2,
    title: "Idiomatic Precision",
    slug: "idiomatik",
    description: "Master idiomatic expressions and collocations like a native.",
    grammarFocus: "Idiomatic expressions collocations and natural phrasing",
    prerequisites: ["c1-02"],
    teachContent: `Near-native German means choosing the **right** word from among synonyms.\n\n**Collocations** (words that naturally go together):\n- eine Entscheidung **treffen** (NOT machen)\n- einen Fehler **begehen** (formal) / **machen** (informal)\n- eine Rolle **spielen** (NOT haben)\n- Kritik **üben** (NOT geben)\n- sich einer Sache **bewusst sein** (NOT wissend sein)\n\n**Idiomatic expressions:**\n- Das liegt **auf der Hand**. (That's obvious.)\n- Er hat **ins Schwarze getroffen**. (He hit the nail on the head.)\n- Ich bin **auf dem Laufenden**. (I'm up to date.)\n- Das geht mir **auf die Nerven**. (That gets on my nerves.)\n\n**Register-appropriate choices:**\n- bekommen (neutral) vs. erhalten (formal) vs. kriegen (colloquial)`,
    drillPrompts: [
      "eine Entscheidung ___ (treffen/machen/nehmen)",
      "Das ___ auf der Hand. (liegt/steht/ist)",
      "Formal for 'bekommen': Die Firma hat den Auftrag ___. (erhalten/gekriegt)",
      "Er hat mit seiner Analyse ins Schwarze ___. (getroffen/geschossen)",
    ],
    writePrompt: "Rewrite 3 sentences replacing generic words (machen, haben, sein) with precise idiomatic collocations.",
    passingScore: 75,
  },
  {
    id: "c2-03",
    cefrLevel: "C2",
    order: 3,
    title: "Academic & Literary Register",
    slug: "academic-register",
    description: "Write with the precision and structure expected in German academia.",
    grammarFocus: "Academic writing conventions nominalization hedging and argumentation",
    prerequisites: ["c1-03", "c1-04"],
    teachContent: `German academic writing has distinct conventions:\n\n**Impersonal constructions:**\n- Es ist **festzustellen**, dass... (It is to be noted that...)\n- Es **lässt sich** zeigen, dass... (It can be shown that...)\n- Man **kann davon ausgehen**, dass... (One can assume that...)\n\n**Hedging (Heckenausdrücke):**\n- Das **dürfte** zutreffend sein. (That is probably correct.)\n- Es **scheint**, als ob... (It seems as though...)\n- **Möglicherweise** ist... (Possibly...)\n\n**Argumentation markers:**\n- **Daraus ergibt sich**, dass... (From this it follows that...)\n- **Im Hinblick auf** (With regard to)\n- **Zusammenfassend lässt sich sagen** (In summary it can be said)\n\n**Nominalization is king:**\n- Instead of: \"Weil wir analysiert haben...\" → \"Aufgrund der **Analyse**...\"`,
    drillPrompts: [
      "Impersonal: 'We can see that...' → Es ___ sich ___, dass...",
      "Hedging: 'This is probably correct.' → Dies ___ zutreffend sein.",
      "Nominalize: 'Weil wir das untersucht haben' → Aufgrund der ___",
      "Conclusion: 'In summary...' → Zusammenfassend ___ sich sagen, dass...",
    ],
    writePrompt: "Write a short academic paragraph (5-6 sentences) arguing for or against a topic of your choice. Use hedging, nominalization, and proper argumentation markers.",
    passingScore: 75,
  },
  {
    id: "c2-04",
    cefrLevel: "C2",
    order: 4,
    title: "Ambiguity Resolution",
    slug: "ambiguity",
    description: "Identify and resolve structural ambiguities in complex German sentences.",
    grammarFocus: "Structural ambiguity resolution and precise sentence construction",
    prerequisites: ["c1-06", "b1-03"],
    teachContent: `Complex German sentences can be ambiguous. C2 mastery means both recognizing and avoiding ambiguity.\n\n**Pronoun reference ambiguity:**\n- Der Mann sah den Jungen. **Er** war müde. (Who was tired?)\n- Fix: Der Mann sah den Jungen. **Der Mann/Dieser** war müde.\n\n**Relative clause attachment:**\n- Die Schwester des Mannes, **die** krank war... (The sister or the man?)\n- Fix: Die Schwester des Mannes, **welche** krank war... (still ambiguous)\n- Better: Die kranke Schwester des Mannes... (restructure)\n\n**Genitive chains:**\n- Die Analyse der Ergebnisse der Studie der Universität (four genitives!)\n- Fix: Die Analyse der Studienergebnisse an der Universität\n\n**Scope ambiguity with negation:**\n- Alle Studenten haben die Prüfung **nicht** bestanden.\n  (None passed? Or not all passed?)`,
    drillPrompts: [
      "Who is 'er'? 'Der Chef rief den Mitarbeiter an. Er war krank.' → Rewrite clearly.",
      "Resolve: 'Die Tochter der Frau, die in Berlin wohnt' → Make it clear who lives in Berlin.",
      "Simplify: 'Die Ergebnisse der Untersuchung der Auswirkungen der Maßnahmen' → ___",
      "Negate clearly: 'All students failed' vs 'Not all students passed' → Write both.",
    ],
    writePrompt: "Find 2 ambiguous German sentences online or create your own. Then rewrite each to resolve the ambiguity in two different ways.",
    passingScore: 75,
  },
  {
    id: "c2-05",
    cefrLevel: "C2",
    order: 5,
    title: "Stylistic Restructuring",
    slug: "stilistik",
    description: "Transform sentences for clarity, rhythm, and impact.",
    grammarFocus: "Stylistic sentence restructuring for clarity emphasis and rhythm",
    prerequisites: ["c1-06", "c2-04"],
    teachContent: `C2 writing is about **choosing** the best structure, not just a correct one.\n\n**Vary sentence openings:**\n- Temporal: **Nachdem** die Ergebnisse vorlagen, ...\n- Participial: **Gestützt auf** die Daten, ...\n- Prepositional: **Angesichts** der Lage, ...\n\n**Rhythm and sentence length:**\n- Mix long, complex sentences with short, punchy ones.\n- Long sentence for explanation. Short for impact. Sehr kurz.\n\n**Active voice for energy:**\n- Weak: Das Problem wurde von der Firma gelöst.\n- Strong: Die Firma löste das Problem.\n\n**Right-branching for readability:**\n- Heavy: Der von der Regierung vor drei Jahren eingeleitete Reformprozess...\n- Better: Der Reformprozess, den die Regierung vor drei Jahren eingeleitet hat, ...\n\n**Parallelism for rhetoric:**\n- Sie kam, sie sah, sie siegte.`,
    drillPrompts: [
      "Rewrite with varied opening: 'Die Firma hat das Problem gelöst, weil...' → ___",
      "Break up: 'Der seit vielen Jahren von internationalen Experten kritisierte Ansatz...' → ___",
      "Add parallelism: 'Die Reform brachte neue Regeln und sie änderte die Gesetze und...' → ___",
      "Active voice: 'Die Entscheidung wurde vom Vorstand getroffen.' → ___",
    ],
    writePrompt: "Take a paragraph of academic text and rewrite it for a newspaper audience: shorter sentences, active voice, varied openings. Then explain what you changed and why.",
    passingScore: 75,
  },
  {
    id: "c2-06",
    cefrLevel: "C2",
    order: 6,
    title: "Near-Native Error Correction",
    slug: "error-correction",
    description: "Identify and fix the subtle errors that distinguish C1 from C2.",
    grammarFocus: "Subtle error detection including register article collocation and word order",
    prerequisites: ["c2-02", "c2-05"],
    teachContent: `At C2, the remaining errors are subtle — things that a grammar checker won't catch.\n\n**Article nuances:**\n- Im Internet (correct) vs. In dem Internet (wrong — fixed expression)\n- In der Schweiz (correct) vs. In Schweiz (wrong — some countries need articles)\n\n**Subtle word order:**\n- \"Er hat mir gestern geholfen\" (natural)\n- \"Er hat gestern mir geholfen\" (emphasizes 'mir' — intentional?)\n\n**Collocation errors:**\n- \"eine Frage stellen\" NOT \"eine Frage fragen\"\n- \"Erfahrungen sammeln\" NOT \"Erfahrungen machen\" (though common)\n\n**Register mismatches:**\n- \"Die Firma hat das Ding gemacht\" (too colloquial for formal)\n- \"Ich möchte Ihnen mitteilen\" in a text message (too formal)\n\n**False friends from English:**\n- bekommen = to get (NOT become)\n- aktuell = current (NOT actual)\n- eventuell = possibly (NOT eventually)`,
    drillPrompts: [
      "Correct: 'Sie hat eine Frage gefragt.' → ___",
      "Correct: 'Ich bin in Schweiz gefahren.' → ___",
      "Correct: 'Er will become a doctor.' → Er will Arzt ___ (werden, not bekommen!)",
      "Is this natural? 'Er hat gestern mir ein Buch gegeben.' → Improve if needed.",
    ],
    writePrompt: "Write a formal email (5-6 sentences) to a German professor requesting a meeting. Then review your own text and annotate any subtle issues you find.",
    passingScore: 75,
  },
];

export function getLessonsByLevel(level: CefrLevel): CurriculumLesson[] {
  return CURRICULUM.filter((l) => l.cefrLevel === level).sort((a, b) => a.order - b.order);
}

export function getLessonById(id: string): CurriculumLesson | undefined {
  return CURRICULUM.find((l) => l.id === id);
}

export function getNextLesson(currentId: string): CurriculumLesson | undefined {
  const current = getLessonById(currentId);
  if (!current) return undefined;

  // Try next in same level
  const sameLevelNext = CURRICULUM.find(
    (l) => l.cefrLevel === current.cefrLevel && l.order === current.order + 1
  );
  if (sameLevelNext) return sameLevelNext;

  // Try first lesson of next level
  const levels: CefrLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];
  const nextLevelIdx = levels.indexOf(current.cefrLevel) + 1;
  if (nextLevelIdx < levels.length) {
    return CURRICULUM.find((l) => l.cefrLevel === levels[nextLevelIdx] && l.order === 1);
  }

  return undefined;
}
